### ISSUE TITLE
Single GPU Training

### ISSUE THREAD

**Issue by mrocr** [herobd/atr#1]
@herobd @cwig  Thank you for your hard work.

What are the changes needed to train on a single GPU?

**Comment by herobd** [comment]
You probably don't want to be using this fork, I'm making edits for a new project. Look at the original project: https://github.com/cwig/start_follow_read

**Comment by herobd** [comment]
As far as your original question goes, I believe the code is written to have the four `continuous_x.py` files running concurrently. You'd need to write a new script that runs the code of those scripts loops in sequence in a master loop.
